// Package gogen emits Go source from versioned IR (AGENTS.md §12).
//
// The translation keeps the interpreter and the generated backend from ever
// drifting apart by delegating almost everything to pkg/runtime, which is a
// thin, exported pass-through onto the same code internal/vm's interpreter
// calls (see internal/vm/export.go). What gogen actually generates is only
// the *control flow*: each ir.Func becomes a Go function whose body is the
// bytecode unrolled into labelled straight-line code, with goto standing in
// for Jump/JumpIfFalse/JumpIfTrue. Locals and captures stay indexed slices of
// *value.Cell exactly as the interpreter's frame keeps them, and the operand
// stack becomes an ordinary Go slice — so a generated function is a direct,
// mechanical transliteration of internal/vm/run.go's execute(), not a
// reimplementation of なでしこ's semantics.
//
// A function that uses エラー監視 additionally gets the run/protect split
// internal/vm/run.go uses: the retry loop lives in nativeN, and the
// recoverable body lives in execN, called fresh on every resume so that a
// panic can be recovered without needing to jump back into a live stack frame
// (Go's recover cannot resume the panicking call; only a new call can).
//
// Scope: everything the interpreter can run, gogen can generate — including
// closures, captures, nested エラー監視, and dynamic (OpCallValue) calls.
// The one thing it refuses is a 非同期関数: suspending and resuming a Go
// call stack outside goroutines has no clean mapping onto generated code, and
// AGENTS.md §12 allows a dynamic feature to be limited rather than forcing
// gogen to reach for one (a caller wanting async can keep using the VM
// backend for that program).
//
// # 速さについて (Apple M4 / darwin-arm64, user時間)
//
//	                          VM        gogen
//	ループ＋算術(500万回)      0.89s     0.84s
//	再帰(フィボナッチ28)       0.47s     0.24s
//
// 関数呼び出しが多いほど有利になる。インタプリタの run/protect/execute の
// 往復とディスパッチが丸ごと無くなるため。算術中心のループでは、演算1回の
// 中身がVMと同じ (internal/ops) なので差は小さい。
//
// この数字に至るまでに踏んだ落とし穴を2つ残しておく。どちらも「薄いから
// 速いはず」という思い込みが外れた例で、プロファイルを見るまで分からない。
//
//   - Machineのメソッド (m.Binary など) は、生成コードの呼び出し位置で
//     インライン展開されない。1演算ごとに余計なフレームを踏み、それだけで
//     全体の約1割を使っていた。pkg/runtime のパッケージ関数 (rt.Binary) は
//     展開される。go build -gcflags=-m で確かめられる
//   - 定数は m.ConstValue(i) で引かず、rt.Number(9) としてソースに直接
//     書く。引くと、定数プールの境界検査と種別のswitchを毎回通る
//
// 残っている一番大きなコストはオペランドスタック (push/pop) で、プロファイル
// 上は約25%。消すには式を直接Goの式へ組み立てる必要があり、「バイトコードの
// 機械的な変換」という今の作りを変えることになる (docs/gogen.md §7)。
package gogen

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"go/format"
	"sort"

	"github.com/kujirahand/nadesiko3go/internal/ir"
)

// Options controls what Generate emits.
type Options struct {
	// Package names the generated file's package. Empty means "main", which
	// also gets a func main() that runs the program against os.Stdout/Stdin.
	Package string
	// Plugins names the plugins beyond plugin_system (PluginNames lists what
	// is known) that the registry prog was compiled against included. Empty
	// means core stdlib only. Generated code's own registry is built with
	// exactly this set — get it wrong and a command silently resolves to the
	// wrong ID instead of failing to compile or run (AGENTS.md §12).
	Plugins []string
}

// Generate translates prog into a single, formatted Go source file that
// imports only "github.com/kujirahand/nadesiko3go/pkg/runtime" (plus the
// standard library), so a build of it needs no Go module inside this
// repository beyond that one dependency.
func Generate(prog *ir.Program, opts Options) ([]byte, error) {
	if err := checkSupported(prog); err != nil {
		return nil, err
	}
	pkg := opts.Package
	if pkg == "" {
		pkg = "main"
	}
	registryCall, err := registryCallFor(opts.Plugins)
	if err != nil {
		return nil, err
	}

	irJSON, err := encodeProgram(prog)
	if err != nil {
		return nil, fmt.Errorf("IRを書き出せません: %w", err)
	}

	g := &generator{prog: prog}
	var funcs bytes.Buffer
	for i := range prog.Funcs {
		g.genFunc(&funcs, i, &prog.Funcs[i])
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by gonako gogen from %s. DO NOT EDIT.\n", sourceName(prog))
	fmt.Fprintf(&out, "package %s\n\n", pkg)
	out.WriteString(`import (
	"encoding/base64"
	"fmt"
	"os"

	rt "github.com/kujirahand/nadesiko3go/pkg/runtime"
)

`)
	fmt.Fprintf(&out, "// irData is the compiled program (AGENTS.md §6), base64 so that no な\n")
	fmt.Fprintf(&out, "// でしこ string literal — which may contain any byte, backtick included —\n")
	fmt.Fprintf(&out, "// can break out of this raw string literal.\n")
	fmt.Fprintf(&out, "const irData = `%s`\n\n", base64.StdEncoding.EncodeToString(irJSON))
	out.WriteString(`// program is decoded once, at package init.
var program = rt.MustDecodeProgram(mustBase64Decode(irData))

func mustBase64Decode(s string) []byte {
	data, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return data
}

// registerNatives wires every Go-compiled function in below in place of the
// bytecode program carries only as metadata (constants, captures, source
// positions — everything callClosure and stdlib commands still need).
func registerNatives(m *rt.Machine) {
`)
	for i := range prog.Funcs {
		fmt.Fprintf(&out, "\tm.SetNative(%d, native%d)\n", i, i)
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(&out, `// Run executes program against host, exactly as the VM backend's Run does —
// registerNatives is the only difference from an ordinary vm.New(...).Run().
func Run(host rt.Host) error {
	m := rt.NewMachine(program, %s, host, rt.DefaultOptions())
	registerNatives(m)
	return m.Run()
}
`, registryCall)
	if pkg == "main" {
		out.WriteString(`
func main() {
	host := rt.NewCUIHost(os.Stdout, os.Stdin, os.Args[1:])
	if err := Run(host); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`)
	}
	out.WriteString("\n")
	out.Write(funcs.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("生成したGoソースが不正です: %w", err)
	}
	return formatted, nil
}

// checkSupported reports the first construct gogen cannot compile, so that a
// caller gets one clear reason rather than a mis-generated file (AGENTS.md
// §12: a dynamic feature may be limited, but it must fail loudly, not
// silently misbehave).
func checkSupported(prog *ir.Program) error {
	var async []string
	for i := range prog.Funcs {
		fn := &prog.Funcs[i]
		if fn.Async {
			async = append(async, fn.Name)
		}
	}
	if len(async) == 0 {
		return nil
	}
	sort.Strings(async)
	return fmt.Errorf("gogenは非同期関数に対応していません（VM実行にフォールバックしてください）: %v", async)
}

func sourceName(prog *ir.Program) string {
	if len(prog.Sources) > 0 && prog.Sources[0].Name != "" {
		return prog.Sources[0].Name
	}
	return "main.nako3"
}
