// Code generated by goyacc _parser_generated.y. DO NOT EDIT.

//line _parser_generated.y:3
//
// なでしこ3 --- 文法定義 (goyaccを利用)
//
// Lexerはgoyaccが要求する形にするため
// nako3/lexerをラップしてこのユニットで使用
//
package parser

import __yyfmt__ "fmt"

//line _parser_generated.y:9
import (
	"fmt"
	"nako3/core"
	"nako3/lexer"
	"nako3/node"
	"nako3/token"
	"nako3/value"
)

//line _parser_generated.y:20
type yySymType struct {
	yys   int
	token *token.Token // lval *yySymType
	node  node.Node
}

const COMMENT = 57346
const FUNC = 57347
const EOF = 57348
const LF = 57349
const EOS = 57350
const COMMA = 57351
const NUMBER = 57352
const STRING = 57353
const STRING_EX = 57354
const WORD = 57355
const WORD_REF = 57356
const IF = 57357
const THEN = 57358
const ELSE = 57359
const BEGIN = 57360
const END = 57361
const FOR = 57362
const KAI = 57363
const AIDA = 57364
const SAKINI = 57365
const TUGINI = 57366
const FOREACH = 57367
const BREAK = 57368
const CONTINUE = 57369
const RETURN = 57370
const TIKUJI = 57371
const LET = 57372
const HENSU = 57373
const TEISU = 57374
const INCLUDE = 57375
const LET_BEGIN = 57376
const ERROR_TRY = 57377
const ERROR = 57378
const DEF_FUNC = 57379
const EQ = 57380
const PLUS = 57381
const MINUS = 57382
const NOT = 57383
const ASTERISK = 57384
const SLASH = 57385
const PERCENT = 57386
const EQEQ = 57387
const NTEQ = 57388
const GT = 57389
const GTEQ = 57390
const LT = 57391
const LTEQ = 57392
const LPAREN = 57393
const RPAREN = 57394
const LBRACKET = 57395
const RBRACKET = 57396
const LBRACE = 57397
const RBRACE = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMMENT",
	"FUNC",
	"EOF",
	"LF",
	"EOS",
	"COMMA",
	"NUMBER",
	"STRING",
	"STRING_EX",
	"WORD",
	"WORD_REF",
	"IF",
	"THEN",
	"ELSE",
	"BEGIN",
	"END",
	"FOR",
	"KAI",
	"AIDA",
	"SAKINI",
	"TUGINI",
	"FOREACH",
	"BREAK",
	"CONTINUE",
	"RETURN",
	"TIKUJI",
	"LET",
	"HENSU",
	"TEISU",
	"INCLUDE",
	"LET_BEGIN",
	"ERROR_TRY",
	"ERROR",
	"DEF_FUNC",
	"EQ",
	"PLUS",
	"MINUS",
	"NOT",
	"ASTERISK",
	"SLASH",
	"PERCENT",
	"EQEQ",
	"NTEQ",
	"GT",
	"GTEQ",
	"LT",
	"LTEQ",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"LBRACE",
	"RBRACE",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line _parser_generated.y:241

var haltError error = nil

type Lexer struct {
	sys       *core.Core
	lexer     *lexer.Lexer
	tokens    token.Tokens
	index     int
	lastToken *token.Token
	result    node.Node
}

func NewLexerWrap(sys *core.Core, src string, fileno int) *Lexer {
	haltError = nil
	lex := Lexer{}
	lex.sys = sys
	lex.lexer = lexer.NewLexer(src, fileno)
	lex.tokens = lex.lexer.Split()
	lex.index = 0
	lex.result = nil
	return &lex
}

// 字句解析の結果をgoyaccに伝える
func (l *Lexer) Lex(lval *yySymType) int {
	if l.index >= len(l.tokens) {
		return -1
	} // last
	if haltError != nil {
		return -1
	}
	// next
	t := l.tokens[l.index]
	l.index++
	lval.token = t
	// return
	result := getTokenNo(t.Type)
	if result == WORD {
		v := l.sys.Globals.Get(t.Literal)
		if v != nil && v.Type == value.Function {
			result = FUNC
			t.Type = token.FUNC
		}
	}
	l.lastToken = t
	if l.sys.IsDebug {
		println("- Lex:", t.ToString())
	}
	return result
}

// エラーを報告する
func (l *Lexer) Error(e string) {
	msg := e
	if msg == "syntax error" {
		msg = "文法エラー"
	}
	t := l.lastToken
	lineno := t.FileInfo.Line
	desc := t.ToString()
	haltError = fmt.Errorf("(%d) %s 理由:"+msg, lineno, desc)
}

// 構文解析を実行する
func Parse(sys *core.Core, src string, fno int) (*node.Node, error) {
	l := NewLexerWrap(sys, src, fno)
	if sys.IsDebug {
		yyDebug = 1
	}
	yyParse(l)
	if haltError != nil {
		return nil, haltError
	}
	return &l.result, nil
}

// 以下 extract_token.nako3 により自動生成
func getTokenNo(token_type token.TType) int {
	switch token_type {
	case token.COMMENT:
		return COMMENT
	case token.FUNC:
		return FUNC
	case token.EOF:
		return EOF
	case token.LF:
		return LF
	case token.EOS:
		return EOS
	case token.COMMA:
		return COMMA
	case token.NUMBER:
		return NUMBER
	case token.STRING:
		return STRING
	case token.STRING_EX:
		return STRING_EX
	case token.WORD:
		return WORD
	case token.WORD_REF:
		return WORD_REF
	case token.IF:
		return IF
	case token.THEN:
		return THEN
	case token.ELSE:
		return ELSE
	case token.BEGIN:
		return BEGIN
	case token.END:
		return END
	case token.FOR:
		return FOR
	case token.KAI:
		return KAI
	case token.AIDA:
		return AIDA
	case token.SAKINI:
		return SAKINI
	case token.TUGINI:
		return TUGINI
	case token.FOREACH:
		return FOREACH
	case token.BREAK:
		return BREAK
	case token.CONTINUE:
		return CONTINUE
	case token.RETURN:
		return RETURN
	case token.TIKUJI:
		return TIKUJI
	case token.LET:
		return LET
	case token.HENSU:
		return HENSU
	case token.TEISU:
		return TEISU
	case token.INCLUDE:
		return INCLUDE
	case token.LET_BEGIN:
		return LET_BEGIN
	case token.ERROR_TRY:
		return ERROR_TRY
	case token.ERROR:
		return ERROR
	case token.DEF_FUNC:
		return DEF_FUNC
	case token.EQ:
		return EQ
	case token.PLUS:
		return PLUS
	case token.MINUS:
		return MINUS
	case token.NOT:
		return NOT
	case token.ASTERISK:
		return ASTERISK
	case token.SLASH:
		return SLASH
	case token.PERCENT:
		return PERCENT
	case token.EQEQ:
		return EQEQ
	case token.NTEQ:
		return NTEQ
	case token.GT:
		return GT
	case token.GTEQ:
		return GTEQ
	case token.LT:
		return LT
	case token.LTEQ:
		return LTEQ
	case token.LPAREN:
		return LPAREN
	case token.RPAREN:
		return RPAREN
	case token.LBRACKET:
		return LBRACKET
	case token.RBRACKET:
		return RBRACKET
	case token.LBRACE:
		return LBRACE
	case token.RBRACE:
		return RBRACE

	}
	panic("[SYSTEM ERROR] parser.y + extract_token.nako3")
	return -1
}

// (メモ) これより下にコードを書かないようにする
// → 行番号が変わらないための対策

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 134

var yyAct = [...]int{

	85, 3, 6, 83, 26, 78, 9, 12, 74, 11,
	10, 73, 23, 24, 25, 15, 33, 17, 63, 45,
	47, 23, 24, 25, 34, 53, 35, 36, 37, 38,
	39, 40, 12, 64, 55, 31, 16, 23, 24, 25,
	34, 41, 50, 51, 62, 20, 65, 66, 23, 24,
	25, 34, 44, 22, 19, 92, 43, 33, 23, 24,
	25, 34, 22, 75, 48, 49, 76, 77, 9, 12,
	81, 82, 10, 18, 23, 24, 25, 15, 22, 17,
	80, 79, 5, 89, 13, 88, 87, 32, 26, 22,
	84, 91, 23, 24, 25, 34, 71, 72, 16, 22,
	68, 67, 90, 69, 70, 52, 11, 10, 46, 56,
	57, 58, 59, 60, 61, 22, 54, 4, 86, 2,
	8, 42, 7, 27, 28, 29, 30, 14, 21, 1,
	0, 0, 0, 22,
}
var yyPact = [...]int{

	2, -1000, 2, -1000, -1000, 99, 99, 99, 99, -1000,
	-1000, -1000, -16, 82, -19, 3, 38, 48, 25, 0,
	-1000, -1000, 27, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 48, -1000, -1000, -1000, 48, 48, 48, 48, 48,
	48, 48, -20, 48, 48, 87, 84, -1000, 48, 48,
	48, 48, -41, -44, 11, -1000, 25, 25, 25, 25,
	25, 25, -1000, 48, 48, -49, 51, 50, 64, 0,
	0, -1000, -1000, -1000, -1000, -1000, -1000, -51, -1000, -1000,
	-1000, 73, 2, -1000, 2, 66, 2, -1000, -1000, 95,
	2, 36, -1000,
}
var yyPgo = [...]int{

	0, 129, 118, 1, 117, 82, 84, 2, 128, 127,
	73, 54, 45, 122, 121, 120, 108, 0,
}
var yyR1 = [...]int{

	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	4, 4, 13, 13, 13, 13, 14, 14, 5, 5,
	5, 6, 6, 8, 8, 8, 8, 7, 9, 9,
	9, 9, 9, 9, 9, 10, 10, 10, 11, 11,
	11, 12, 12, 12, 15, 15, 15, 15, 16, 17,
}
var yyR2 = [...]int{

	0, 1, 1, 2, 1, 2, 2, 2, 2, 1,
	1, 1, 3, 4, 4, 4, 3, 4, 1, 2,
	4, 1, 2, 1, 1, 1, 1, 1, 1, 3,
	3, 3, 3, 3, 3, 1, 3, 3, 1, 3,
	3, 1, 3, 3, 4, 6, 6, 9, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, -5, -7, -13, -15, 4,
	8, 7, 5, -6, -9, 13, 34, 15, -10, -11,
	-12, -8, 51, 10, 11, 12, -3, -4, -4, -4,
	-4, 51, 5, -7, 13, 45, 46, 47, 48, 49,
	50, 38, -14, 53, 14, -7, -16, -7, 39, 40,
	42, 43, -5, -7, -6, -7, -10, -10, -10, -10,
	-10, -10, -7, 38, 53, -7, -7, 14, 16, -11,
	-11, -12, -12, 52, 52, 52, -7, -7, 54, 30,
	30, -3, 7, 54, 17, -17, -2, -3, 19, 17,
	7, -17, 19,
}
var yyDef = [...]int{

	0, -2, 1, 2, 4, 0, 21, 0, 0, 9,
	10, 11, 18, 0, 27, 26, 0, 0, 28, 35,
	38, 41, 0, 23, 24, 25, 3, 5, 6, 7,
	8, 0, 19, 22, 26, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 48, 0, 0,
	0, 0, 0, 21, 0, 21, 29, 30, 31, 32,
	33, 34, 12, 0, 0, 0, 0, 0, 0, 36,
	37, 39, 40, 42, 43, 20, 13, 0, 16, 14,
	15, 44, 11, 17, 0, 0, 49, 45, 46, 0,
	0, 0, 47,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:34
		{
			yyVAL.node = yyDollar[1].node
			yylex.(*Lexer).result = yyVAL.node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:41
		{
			n := node.NewNodeSentence(yyDollar[1].node.GetFileInfo())
			n.Append(yyDollar[1].node)
			yyVAL.node = n
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line _parser_generated.y:47
		{
			n, _ := yyDollar[1].node.(node.NodeSentence)
			n.Append(yyDollar[2].node)
			yyVAL.node = n
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:60
		{
			yyVAL.node = node.NewNodeNop(yyDollar[1].token)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:66
		{
			yyVAL.node = node.NewNodeNop(yyDollar[1].token)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:70
		{
			yyVAL.node = node.NewNodeNop(yyDollar[1].token)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:76
		{
			yyVAL.node = node.NewNodeLet(yyDollar[1].token, node.NewNodeList(), yyDollar[3].node)
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:80
		{
			n := yyDollar[2].node.(node.NodeList)
			yyVAL.node = node.NewNodeLet(yyDollar[1].token, n, yyDollar[4].node)
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:85
		{
			yyVAL.node = node.NewNodeLet(yyDollar[2].token, node.NewNodeList(), yyDollar[3].node)
		}
	case 15:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:89
		{
			yyVAL.node = node.NewNodeLet(yyDollar[3].token, node.NewNodeList(), yyDollar[2].node)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:95
		{
			n := node.NodeList{yyDollar[2].node}
			yyVAL.node = n
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:100
		{
			n := yyDollar[1].node.(node.NodeList)
			yyVAL.node = append(n, yyDollar[3].node)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:107
		{
			yyVAL.node = node.NewNodeCallFunc(yyDollar[1].token)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line _parser_generated.y:111
		{
			n := node.NewNodeCallFunc(yyDollar[2].token)
			n.Args, _ = yyDollar[1].node.(node.NodeList)
			yyVAL.node = n
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:117
		{
			n := node.NewNodeCallFunc(yyDollar[1].token)
			n.Args, _ = yyDollar[3].node.(node.NodeList)
			yyVAL.node = n
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:125
		{
			n := node.NodeList{yyDollar[1].node}
			yyVAL.node = n
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line _parser_generated.y:130
		{
			args, _ := yyDollar[1].node.(node.NodeList)
			n := append(args, yyDollar[2].node)
			yyVAL.node = n
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:138
		{
			yyVAL.node = node.NewNodeConst(value.Float, yyDollar[1].token)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:142
		{
			yyVAL.node = node.NewNodeConst(value.Str, yyDollar[1].token)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:146
		{
			yyVAL.node = node.NewNodeConst(value.Str, yyDollar[1].token)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line _parser_generated.y:150
		{
			yyVAL.node = node.NewNodeWord(yyDollar[1].token)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:160
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:164
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:168
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:172
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:176
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:180
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:187
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:191
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:198
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:202
		{
			yyVAL.node = node.NewNodeOperator(yyDollar[2].token, yyDollar[1].node, yyDollar[3].node)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:209
		{
			yyVAL.node = node.NewNodeCalc(yyDollar[3].token, yyDollar[2].node)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line _parser_generated.y:213
		{
			yyVAL.node = node.NewNodeCalc(yyDollar[3].token, yyDollar[2].node)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line _parser_generated.y:219
		{
			yyVAL.node = node.NewNodeIf(yyDollar[1].token, yyDollar[2].node, yyDollar[4].node, node.NewNodeNop(yyDollar[1].token))
		}
	case 45:
		yyDollar = yyS[yypt-6 : yypt+1]
//line _parser_generated.y:223
		{
			yyVAL.node = node.NewNodeIf(yyDollar[1].token, yyDollar[2].node, yyDollar[4].node, yyDollar[6].node)
		}
	case 46:
		yyDollar = yyS[yypt-6 : yypt+1]
//line _parser_generated.y:227
		{
			yyVAL.node = node.NewNodeIf(yyDollar[1].token, yyDollar[2].node, yyDollar[5].node, node.NewNodeNop(yyDollar[1].token))
		}
	case 47:
		yyDollar = yyS[yypt-9 : yypt+1]
//line _parser_generated.y:231
		{
			yyVAL.node = node.NewNodeIf(yyDollar[1].token, yyDollar[2].node, yyDollar[5].node, yyDollar[8].node)
		}
	}
	goto yystack /* stack new state and value */
}
