
// Code generated by extract_token.nako3 and token/token.go DO NOT EDIT.
package parser
import (
	"github.com/kujirahand/nadesiko3go/token"
)

// このファイルは、extract_token.nako3 により自動生成
func getTokenNo(token_type token.TType) int {
	switch token_type {
  case token.UNKNOWN: return UNKNOWN
  case token.COMMENT: return COMMENT
  case token.FUNC: return FUNC
  case token.EOF: return EOF
  case token.LF: return LF
  case token.EOS: return EOS
  case token.EOS4ELSE: return EOS4ELSE
  case token.COMMA: return COMMA
  case token.NUMBER: return NUMBER
  case token.STRING: return STRING
  case token.STRING_EX: return STRING_EX
  case token.WORD: return WORD
  case token.WORD_REF: return WORD_REF
  case token.AND: return AND
  case token.OR: return OR
  case token.IF: return IF
  case token.THEN: return THEN
  case token.THEN_SINGLE: return THEN_SINGLE
  case token.ELSE: return ELSE
  case token.ELSE_SINGLE: return ELSE_SINGLE
  case token.BEGIN: return BEGIN
  case token.END: return END
  case token.AIDA: return AIDA
  case token.WHILE_BEGIN: return WHILE_BEGIN
  case token.FOREACH_BEGIN: return FOREACH_BEGIN
  case token.FOREACH: return FOREACH
  case token.FOREACH_SINGLE: return FOREACH_SINGLE
  case token.FOR_BEGIN: return FOR_BEGIN
  case token.FOR: return FOR
  case token.FOR_SINGLE: return FOR_SINGLE
  case token.KAI_BEGIN: return KAI_BEGIN
  case token.KAI: return KAI
  case token.KAI_SINGLE: return KAI_SINGLE
  case token.SAKINI: return SAKINI
  case token.TUGINI: return TUGINI
  case token.BREAK: return BREAK
  case token.CONTINUE: return CONTINUE
  case token.RETURN: return RETURN
  case token.TIKUJI: return TIKUJI
  case token.LET: return LET
  case token.HENSU: return HENSU
  case token.TEISU: return TEISU
  case token.INCLUDE: return INCLUDE
  case token.LET_BEGIN: return LET_BEGIN
  case token.BEGIN_CALLFUNC: return BEGIN_CALLFUNC
  case token.ERROR_TRY: return ERROR_TRY
  case token.ERROR: return ERROR
  case token.DEF_FUNC: return DEF_FUNC
  case token.EQ: return EQ
  case token.PLUS: return PLUS
  case token.STR_PLUS: return STR_PLUS
  case token.MINUS: return MINUS
  case token.NOT: return NOT
  case token.MUL: return MUL
  case token.DIV: return DIV
  case token.MOD: return MOD
  case token.EXP: return EXP
  case token.EQEQ: return EQEQ
  case token.NTEQ: return NTEQ
  case token.GT: return GT
  case token.GTEQ: return GTEQ
  case token.LT: return LT
  case token.LTEQ: return LTEQ
  case token.LPAREN: return LPAREN
  case token.RPAREN: return RPAREN
  case token.LBRACKET: return LBRACKET
  case token.RBRACKET: return RBRACKET
  case token.LBRACE: return LBRACE
  case token.RBRACE: return RBRACE
  case token.COLON: return COLON

	}
	panic("[SYSTEM ERROR] parser.y + extract_token.nako3")
	// return -1
}
